version: "3.8"

services:
  payjoy_php:
    #user: "501:502"
    build:
      context: ./
      dockerfile: php70pj.dockerfile
    image: payjoy-centos7-apache2.4-php7
    container_name:
      php_70_pj
    volumes:
      - ../tasks:/var/www/html
      - ../credentials:/var/www/credentials
      - ./logs/:/var/log/httpd
    ports:
      - '80:80'
    expose:
      - '80'
    depends_on:
      - payjoy_mysql
  payjoy_mysql:
    image: mysql:5.7.34
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

    volumes:
      - ./data:/var/lib/mysql
      - ../tasks:/docker-entrypoint-initdb.d
    ports:
      - '127.0.0.1:3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
volumes:
  persistent: {}
